In [1]:
import os, sys
import pickle
import json
from sklearn.linear_model import SGDClassifier as svm
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

In [2]:
cwd = os.getcwd()

#Read training data
f = open(os.path.join(cwd, r'training.pkl'), 'rb')
(X_data, X_label) = pickle.load(f)
f.close()

#Read test data
f = open(os.path.join(cwd, r'testing.pkl'), 'rb')
(Y_data, Y_label) = pickle.load(f)
f.close()

In [3]:
train = []
trainLabel = []

label2no = {u'support':0, u'query':1, u'deny':2, u'comment':3}

#Convert list of lists to nd array (Required for SVM Training)
for key in X_label.keys():
    train.append(X_data[key])
    trainLabel.append(label2no[X_label[key]])

train = np.array(train)
trainLabel = np.array(trainLabel)
#SVM Training
svm_clf = svm(loss='squared_hinge', max_iter=1000).fit(train, trainLabel.transpose())

test = []
testLabel = []

for key in Y_label.keys():
    test.append(Y_data[key])
    testLabel.append(label2no[Y_label[key]])

test = np.array(test)
testLabel = np.array(testLabel)

In [4]:
#SVM Testing
print("\nSVM Classifier Report\n")
predicted = svm_clf.predict(test)
print("Classification accuracy: ", accuracy_score(testLabel, predicted))
print("Confusion matrix: ", confusion_matrix(testLabel, predicted))
target_names = ['support', 'query', 'deny', 'comment']
print(classification_report(testLabel, predicted, target_names=target_names))


SVM Classifier Report

Classification accuracy:  0.6873212583412774
Confusion matrix:  [[ 23   0  11  60]
 [  0   1  29  76]
 [  1   0   7  63]
 [ 10   0  78 690]]
              precision    recall  f1-score   support

     support       0.68      0.24      0.36        94
       query       1.00      0.01      0.02       106
        deny       0.06      0.10      0.07        71
     comment       0.78      0.89      0.83       778

    accuracy                           0.69      1049
   macro avg       0.63      0.31      0.32      1049
weighted avg       0.74      0.69      0.65      1049

